import allure
from base.base_test import BaseTest

@allure.feature("Planning meeting functionality")
class TestPlanningMeeting(BaseTest):
    @allure.title("Creating meeting")
    @allure.severity("Critical")
    def test_meeting_scheduling(self, user_1):
        self.login_page.open()
        self.login_page.enter_login(self.data.LOGIN)
        self.login_page.enter_password(self.data.PASSWORD)
        self.login_page.click_submit_button()
        self.main_page.is_opened()
        self.main_page.click_on_planning_meet_button()
        self.planning_meet_page.is_opened()
        self.planning_meet_page.add_topic()
        self.planning_meet_page.add_meet_password()
        self.planning_meet_page.add_meet_description()
        self.planning_meet_page.save_schedule()
        self.planning_meet_page.topic_name_is_saved()
        self.planning_meet_page.meet_password_is_saved()
        self.planning_meet_page.meet_description_is_saved()
        self.planning_meet_page.make_screenshot("The meeting has been created")
        self.planning_meet_page.click_on_close_schedule_meeting_button()
        self.main_page.is_opened()
        self.main_page.click_on_planned_name_meet()
        self.main_page.click_on_delete_meet_button()
        self.main_page.click_on_confirm_action_button()

    @allure.title("Adding users in planning meeting")
    @allure.severity("Critical")
    def test_adding_user_in_planning_meeting(self, user_1):
        self.login_page.open()
        self.login_page.enter_login(self.data.LOGIN)
        self.login_page.enter_password(self.data.PASSWORD)
        self.login_page.click_submit_button()
        self.main_page.is_opened()
        self.main_page.click_on_planning_meet_button()
        self.planning_meet_page.is_opened()
        self.planning_meet_page.add_topic()
        self.planning_meet_page.click_user_tab_button()
        self.planning_meet_page.select_user()
        self.planning_meet_page.save_schedule()
        self.planning_meet_page.click_on_user_avatar_button()
        self.planning_meet_page.click_on_logout_button()
        self.login_page.is_opened()
        self.login_page.clear_login()
        self.login_page.enter_login(self.data.LOGIN2)
        self.login_page.clear_password()
        self.login_page.enter_password(self.data.PASSWORD2)
        self.login_page.click_submit_button()
        self.main_page.is_opened()
        self.planning_meet_page.check_planned_meet()
        self.planning_meet_page.make_screenshot("User has been added")

